---
dependencies: []

galaxy_info:
  author: Artur Komarov
  description: K3s Cluster Complete Audit Role
  company: KomarovAI
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - k3s
    - kubernetes
    - audit
    - monitoring
    - security
